### ISSUE TITLE
[Bug report] Reading matrix element tables

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#80]
Attempting to create a `FluxQubit` object, write a matrix element table to file then read it back in leads to an exception
```
scq.FluxQubit.create()
matelem_FQ = FQ.matrixelement_table('n_1_operator', evecs=None, evals_count=12, filename='FQ_5.hdf5')
matelem_FQ_from_file = SpectrumData.create_from_file(filename='FQ_5.hdf5')
```
Here is the Traceback:

```
Traceback (most recent call last):
  File "/Users/danny/PycharmProjects/scqubits/examples/FQ_flux_plots.py", line 55, in <module>
    matelem_CM_from_file = SpectrumData.create_from_file(filename='FQ_5.hdf5')
  File "/Users/danny/PycharmProjects/scqubits/scqubits/io_utils/fileio_serializers.py", line 105, in create_from_file
    return io.read(filename)
  File "/Users/danny/PycharmProjects/scqubits/scqubits/io_utils/fileio.py", line 108, in read
    return deserialize(iodata)
  File "/Users/danny/PycharmProjects/scqubits/scqubits/io_utils/fileio.py", line 62, in deserialize
    return cls.deserialize(iodata)
  File "/Users/danny/PycharmProjects/scqubits/scqubits/io_utils/fileio_serializers.py", line 66, in deserialize
    return cls(**io_data.as_kwargs())
TypeError: __init__() missing 1 required positional argument: 'energy_table'

Process finished with exit code 1

```

**Comment by jkochNU** [comment]
@dkweiss31 Please let me know whether the fix works as expected.

**Comment by dkweiss31** [comment]
Indeed, the fix works as expected. Many thanks.
